// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: McuCmdMsg.proto

package com.addrobots.protobuf;

public final class McuCmdMsg {
  private McuCmdMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MotorCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MotorCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 num = 1;</code>
     */
    int getNum();

    /**
     * <code>optional int32 dir = 2;</code>
     */
    int getDir();

    /**
     * <code>optional double degSec = 3;</code>
     */
    double getDegSec();

    /**
     * <code>optional double aDegSec = 4;</code>
     */
    double getADegSec();
  }
  /**
   * Protobuf type {@code MotorCmd}
   */
  public  static final class MotorCmd extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MotorCmd)
      MotorCmdOrBuilder {
    // Use MotorCmd.newBuilder() to construct.
    private MotorCmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MotorCmd() {
      num_ = 0;
      dir_ = 0;
      degSec_ = 0D;
      aDegSec_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MotorCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              num_ = input.readInt32();
              break;
            }
            case 16: {

              dir_ = input.readInt32();
              break;
            }
            case 25: {

              degSec_ = input.readDouble();
              break;
            }
            case 33: {

              aDegSec_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_MotorCmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_MotorCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.McuCmdMsg.MotorCmd.class, com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder.class);
    }

    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>optional int32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int DIR_FIELD_NUMBER = 2;
    private int dir_;
    /**
     * <code>optional int32 dir = 2;</code>
     */
    public int getDir() {
      return dir_;
    }

    public static final int DEGSEC_FIELD_NUMBER = 3;
    private double degSec_;
    /**
     * <code>optional double degSec = 3;</code>
     */
    public double getDegSec() {
      return degSec_;
    }

    public static final int ADEGSEC_FIELD_NUMBER = 4;
    private double aDegSec_;
    /**
     * <code>optional double aDegSec = 4;</code>
     */
    public double getADegSec() {
      return aDegSec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (num_ != 0) {
        output.writeInt32(1, num_);
      }
      if (dir_ != 0) {
        output.writeInt32(2, dir_);
      }
      if (degSec_ != 0D) {
        output.writeDouble(3, degSec_);
      }
      if (aDegSec_ != 0D) {
        output.writeDouble(4, aDegSec_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      if (dir_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dir_);
      }
      if (degSec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, degSec_);
      }
      if (aDegSec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, aDegSec_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.McuCmdMsg.MotorCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MotorCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MotorCmd)
        com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_MotorCmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_MotorCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.McuCmdMsg.MotorCmd.class, com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder.class);
      }

      // Construct using com.addrobots.protobuf.McuCmdMsg.MotorCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        num_ = 0;

        dir_ = 0;

        degSec_ = 0D;

        aDegSec_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_MotorCmd_descriptor;
      }

      public com.addrobots.protobuf.McuCmdMsg.MotorCmd getDefaultInstanceForType() {
        return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
      }

      public com.addrobots.protobuf.McuCmdMsg.MotorCmd build() {
        com.addrobots.protobuf.McuCmdMsg.MotorCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.McuCmdMsg.MotorCmd buildPartial() {
        com.addrobots.protobuf.McuCmdMsg.MotorCmd result = new com.addrobots.protobuf.McuCmdMsg.MotorCmd(this);
        result.num_ = num_;
        result.dir_ = dir_;
        result.degSec_ = degSec_;
        result.aDegSec_ = aDegSec_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.McuCmdMsg.MotorCmd) {
          return mergeFrom((com.addrobots.protobuf.McuCmdMsg.MotorCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.McuCmdMsg.MotorCmd other) {
        if (other == com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance()) return this;
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (other.getDir() != 0) {
          setDir(other.getDir());
        }
        if (other.getDegSec() != 0D) {
          setDegSec(other.getDegSec());
        }
        if (other.getADegSec() != 0D) {
          setADegSec(other.getADegSec());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.McuCmdMsg.MotorCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.McuCmdMsg.MotorCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int num_ ;
      /**
       * <code>optional int32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 1;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 1;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private int dir_ ;
      /**
       * <code>optional int32 dir = 2;</code>
       */
      public int getDir() {
        return dir_;
      }
      /**
       * <code>optional int32 dir = 2;</code>
       */
      public Builder setDir(int value) {
        
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dir = 2;</code>
       */
      public Builder clearDir() {
        
        dir_ = 0;
        onChanged();
        return this;
      }

      private double degSec_ ;
      /**
       * <code>optional double degSec = 3;</code>
       */
      public double getDegSec() {
        return degSec_;
      }
      /**
       * <code>optional double degSec = 3;</code>
       */
      public Builder setDegSec(double value) {
        
        degSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double degSec = 3;</code>
       */
      public Builder clearDegSec() {
        
        degSec_ = 0D;
        onChanged();
        return this;
      }

      private double aDegSec_ ;
      /**
       * <code>optional double aDegSec = 4;</code>
       */
      public double getADegSec() {
        return aDegSec_;
      }
      /**
       * <code>optional double aDegSec = 4;</code>
       */
      public Builder setADegSec(double value) {
        
        aDegSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double aDegSec = 4;</code>
       */
      public Builder clearADegSec() {
        
        aDegSec_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:MotorCmd)
    }

    // @@protoc_insertion_point(class_scope:MotorCmd)
    private static final com.addrobots.protobuf.McuCmdMsg.MotorCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.McuCmdMsg.MotorCmd();
    }

    public static com.addrobots.protobuf.McuCmdMsg.MotorCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MotorCmd>
        PARSER = new com.google.protobuf.AbstractParser<MotorCmd>() {
      public MotorCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MotorCmd(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MotorCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MotorCmd> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.McuCmdMsg.MotorCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SensorCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional double value = 2;</code>
     */
    double getValue();

    /**
     * <code>optional string unit = 3;</code>
     */
    java.lang.String getUnit();
    /**
     * <code>optional string unit = 3;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();
  }
  /**
   * Protobuf type {@code SensorCmd}
   */
  public  static final class SensorCmd extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SensorCmd)
      SensorCmdOrBuilder {
    // Use SensorCmd.newBuilder() to construct.
    private SensorCmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SensorCmd() {
      name_ = "";
      value_ = 0D;
      unit_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SensorCmd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 17: {

              value_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              unit_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_SensorCmd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_SensorCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.McuCmdMsg.SensorCmd.class, com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>optional double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    private volatile java.lang.Object unit_;
    /**
     * <code>optional string unit = 3;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>optional string unit = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (value_ != 0D) {
        output.writeDouble(2, value_);
      }
      if (!getUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, unit_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      if (!getUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, unit_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.McuCmdMsg.SensorCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SensorCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SensorCmd)
        com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_SensorCmd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_SensorCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.McuCmdMsg.SensorCmd.class, com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder.class);
      }

      // Construct using com.addrobots.protobuf.McuCmdMsg.SensorCmd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        value_ = 0D;

        unit_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_SensorCmd_descriptor;
      }

      public com.addrobots.protobuf.McuCmdMsg.SensorCmd getDefaultInstanceForType() {
        return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
      }

      public com.addrobots.protobuf.McuCmdMsg.SensorCmd build() {
        com.addrobots.protobuf.McuCmdMsg.SensorCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.McuCmdMsg.SensorCmd buildPartial() {
        com.addrobots.protobuf.McuCmdMsg.SensorCmd result = new com.addrobots.protobuf.McuCmdMsg.SensorCmd(this);
        result.name_ = name_;
        result.value_ = value_;
        result.unit_ = unit_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.McuCmdMsg.SensorCmd) {
          return mergeFrom((com.addrobots.protobuf.McuCmdMsg.SensorCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.McuCmdMsg.SensorCmd other) {
        if (other == com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.McuCmdMsg.SensorCmd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.McuCmdMsg.SensorCmd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>optional double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>optional string unit = 3;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string unit = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string unit = 3;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string unit = 3;</code>
       */
      public Builder clearUnit() {
        
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>optional string unit = 3;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unit_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SensorCmd)
    }

    // @@protoc_insertion_point(class_scope:SensorCmd)
    private static final com.addrobots.protobuf.McuCmdMsg.SensorCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.McuCmdMsg.SensorCmd();
    }

    public static com.addrobots.protobuf.McuCmdMsg.SensorCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorCmd>
        PARSER = new com.google.protobuf.AbstractParser<SensorCmd>() {
      public SensorCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SensorCmd(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SensorCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorCmd> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.McuCmdMsg.SensorCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface McuWrapperMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:McuWrapperMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .MotorCmd motorCmd = 1;</code>
     */
    com.addrobots.protobuf.McuCmdMsg.MotorCmd getMotorCmd();
    /**
     * <code>optional .MotorCmd motorCmd = 1;</code>
     */
    com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder getMotorCmdOrBuilder();

    /**
     * <code>optional .SensorCmd sensorCmd = 2;</code>
     */
    com.addrobots.protobuf.McuCmdMsg.SensorCmd getSensorCmd();
    /**
     * <code>optional .SensorCmd sensorCmd = 2;</code>
     */
    com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder getSensorCmdOrBuilder();

    public com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code McuWrapperMessage}
   */
  public  static final class McuWrapperMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:McuWrapperMessage)
      McuWrapperMessageOrBuilder {
    // Use McuWrapperMessage.newBuilder() to construct.
    private McuWrapperMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private McuWrapperMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private McuWrapperMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(com.addrobots.protobuf.McuCmdMsg.MotorCmd.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(com.addrobots.protobuf.McuCmdMsg.SensorCmd.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_McuWrapperMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.McuCmdMsg.internal_static_McuWrapperMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.class, com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      MOTORCMD(1),
      SENSORCMD(2),
      MSG_NOT_SET(0);
      private int value = 0;
      private MsgCase(int value) {
        this.value = value;
      }
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return MOTORCMD;
          case 2: return SENSORCMD;
          case 0: return MSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int MOTORCMD_FIELD_NUMBER = 1;
    /**
     * <code>optional .MotorCmd motorCmd = 1;</code>
     */
    public com.addrobots.protobuf.McuCmdMsg.MotorCmd getMotorCmd() {
      if (msgCase_ == 1) {
         return (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_;
      }
      return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
    }
    /**
     * <code>optional .MotorCmd motorCmd = 1;</code>
     */
    public com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder getMotorCmdOrBuilder() {
      if (msgCase_ == 1) {
         return (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_;
      }
      return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
    }

    public static final int SENSORCMD_FIELD_NUMBER = 2;
    /**
     * <code>optional .SensorCmd sensorCmd = 2;</code>
     */
    public com.addrobots.protobuf.McuCmdMsg.SensorCmd getSensorCmd() {
      if (msgCase_ == 2) {
         return (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_;
      }
      return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
    }
    /**
     * <code>optional .SensorCmd sensorCmd = 2;</code>
     */
    public com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder getSensorCmdOrBuilder() {
      if (msgCase_ == 2) {
         return (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_;
      }
      return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code McuWrapperMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:McuWrapperMessage)
        com.addrobots.protobuf.McuCmdMsg.McuWrapperMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_McuWrapperMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_McuWrapperMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.class, com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.Builder.class);
      }

      // Construct using com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.McuCmdMsg.internal_static_McuWrapperMessage_descriptor;
      }

      public com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage getDefaultInstanceForType() {
        return com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.getDefaultInstance();
      }

      public com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage build() {
        com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage buildPartial() {
        com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage result = new com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage(this);
        if (msgCase_ == 1) {
          if (motorCmdBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = motorCmdBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (sensorCmdBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = sensorCmdBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage) {
          return mergeFrom((com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage other) {
        if (other == com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case MOTORCMD: {
            mergeMotorCmd(other.getMotorCmd());
            break;
          }
          case SENSORCMD: {
            mergeSensorCmd(other.getSensorCmd());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.McuCmdMsg.MotorCmd, com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder> motorCmdBuilder_;
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.MotorCmd getMotorCmd() {
        if (motorCmdBuilder_ == null) {
          if (msgCase_ == 1) {
            return (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_;
          }
          return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return motorCmdBuilder_.getMessage();
          }
          return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
        }
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public Builder setMotorCmd(com.addrobots.protobuf.McuCmdMsg.MotorCmd value) {
        if (motorCmdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          motorCmdBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public Builder setMotorCmd(
          com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder builderForValue) {
        if (motorCmdBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          motorCmdBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public Builder mergeMotorCmd(com.addrobots.protobuf.McuCmdMsg.MotorCmd value) {
        if (motorCmdBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance()) {
            msg_ = com.addrobots.protobuf.McuCmdMsg.MotorCmd.newBuilder((com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            motorCmdBuilder_.mergeFrom(value);
          }
          motorCmdBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public Builder clearMotorCmd() {
        if (motorCmdBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          motorCmdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder getMotorCmdBuilder() {
        return getMotorCmdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder getMotorCmdOrBuilder() {
        if ((msgCase_ == 1) && (motorCmdBuilder_ != null)) {
          return motorCmdBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_;
          }
          return com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
        }
      }
      /**
       * <code>optional .MotorCmd motorCmd = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.McuCmdMsg.MotorCmd, com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder> 
          getMotorCmdFieldBuilder() {
        if (motorCmdBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = com.addrobots.protobuf.McuCmdMsg.MotorCmd.getDefaultInstance();
          }
          motorCmdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.addrobots.protobuf.McuCmdMsg.MotorCmd, com.addrobots.protobuf.McuCmdMsg.MotorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.MotorCmdOrBuilder>(
                  (com.addrobots.protobuf.McuCmdMsg.MotorCmd) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return motorCmdBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.McuCmdMsg.SensorCmd, com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder> sensorCmdBuilder_;
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.SensorCmd getSensorCmd() {
        if (sensorCmdBuilder_ == null) {
          if (msgCase_ == 2) {
            return (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_;
          }
          return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return sensorCmdBuilder_.getMessage();
          }
          return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public Builder setSensorCmd(com.addrobots.protobuf.McuCmdMsg.SensorCmd value) {
        if (sensorCmdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          sensorCmdBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public Builder setSensorCmd(
          com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder builderForValue) {
        if (sensorCmdBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          sensorCmdBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public Builder mergeSensorCmd(com.addrobots.protobuf.McuCmdMsg.SensorCmd value) {
        if (sensorCmdBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance()) {
            msg_ = com.addrobots.protobuf.McuCmdMsg.SensorCmd.newBuilder((com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            sensorCmdBuilder_.mergeFrom(value);
          }
          sensorCmdBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public Builder clearSensorCmd() {
        if (sensorCmdBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          sensorCmdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder getSensorCmdBuilder() {
        return getSensorCmdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      public com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder getSensorCmdOrBuilder() {
        if ((msgCase_ == 2) && (sensorCmdBuilder_ != null)) {
          return sensorCmdBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_;
          }
          return com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
        }
      }
      /**
       * <code>optional .SensorCmd sensorCmd = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.McuCmdMsg.SensorCmd, com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder> 
          getSensorCmdFieldBuilder() {
        if (sensorCmdBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = com.addrobots.protobuf.McuCmdMsg.SensorCmd.getDefaultInstance();
          }
          sensorCmdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.addrobots.protobuf.McuCmdMsg.SensorCmd, com.addrobots.protobuf.McuCmdMsg.SensorCmd.Builder, com.addrobots.protobuf.McuCmdMsg.SensorCmdOrBuilder>(
                  (com.addrobots.protobuf.McuCmdMsg.SensorCmd) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return sensorCmdBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:McuWrapperMessage)
    }

    // @@protoc_insertion_point(class_scope:McuWrapperMessage)
    private static final com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage();
    }

    public static com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<McuWrapperMessage>
        PARSER = new com.google.protobuf.AbstractParser<McuWrapperMessage>() {
      public McuWrapperMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new McuWrapperMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<McuWrapperMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<McuWrapperMessage> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.McuCmdMsg.McuWrapperMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MotorCmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MotorCmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorCmd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SensorCmd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_McuWrapperMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_McuWrapperMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017McuCmdMsg.proto\"E\n\010MotorCmd\022\013\n\003num\030\001 \001" +
      "(\005\022\013\n\003dir\030\002 \001(\005\022\016\n\006degSec\030\003 \001(\001\022\017\n\007aDegS" +
      "ec\030\004 \001(\001\"6\n\tSensorCmd\022\014\n\004name\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\001\022\014\n\004unit\030\003 \001(\t\"Z\n\021McuWrapperMe" +
      "ssage\022\035\n\010motorCmd\030\001 \001(\0132\t.MotorCmdH\000\022\037\n\t" +
      "sensorCmd\030\002 \001(\0132\n.SensorCmdH\000B\005\n\003msgB\030\n\026" +
      "com.addrobots.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MotorCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MotorCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MotorCmd_descriptor,
        new java.lang.String[] { "Num", "Dir", "DegSec", "ADegSec", });
    internal_static_SensorCmd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SensorCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SensorCmd_descriptor,
        new java.lang.String[] { "Name", "Value", "Unit", });
    internal_static_McuWrapperMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_McuWrapperMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_McuWrapperMessage_descriptor,
        new java.lang.String[] { "MotorCmd", "SensorCmd", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
