// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VcuCmdMsg.proto

package com.addrobots.protobuf;

public final class VcuCmdMsg {
  private VcuCmdMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DriveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Drive)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double velocity = 1;</code>
     */
    double getVelocity();

    /**
     * <code>optional string direction = 2;</code>
     */
    java.lang.String getDirection();
    /**
     * <code>optional string direction = 2;</code>
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>optional double acceleration = 3;</code>
     */
    double getAcceleration();

    /**
     * <code>optional double distance = 4;</code>
     */
    double getDistance();

    /**
     * <code>optional double edgeDistance = 5;</code>
     */
    double getEdgeDistance();

    /**
     * <code>optional string edgeSide = 6;</code>
     */
    java.lang.String getEdgeSide();
    /**
     * <code>optional string edgeSide = 6;</code>
     */
    com.google.protobuf.ByteString
        getEdgeSideBytes();
  }
  /**
   * Protobuf type {@code Drive}
   */
  public  static final class Drive extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Drive)
      DriveOrBuilder {
    // Use Drive.newBuilder() to construct.
    private Drive(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Drive() {
      velocity_ = 0D;
      direction_ = "";
      acceleration_ = 0D;
      distance_ = 0D;
      edgeDistance_ = 0D;
      edgeSide_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Drive(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              velocity_ = input.readDouble();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 25: {

              acceleration_ = input.readDouble();
              break;
            }
            case 33: {

              distance_ = input.readDouble();
              break;
            }
            case 41: {

              edgeDistance_ = input.readDouble();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              edgeSide_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Drive_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Drive_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.VcuCmdMsg.Drive.class, com.addrobots.protobuf.VcuCmdMsg.Drive.Builder.class);
    }

    public static final int VELOCITY_FIELD_NUMBER = 1;
    private double velocity_;
    /**
     * <code>optional double velocity = 1;</code>
     */
    public double getVelocity() {
      return velocity_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object direction_;
    /**
     * <code>optional string direction = 2;</code>
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>optional string direction = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCELERATION_FIELD_NUMBER = 3;
    private double acceleration_;
    /**
     * <code>optional double acceleration = 3;</code>
     */
    public double getAcceleration() {
      return acceleration_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 4;
    private double distance_;
    /**
     * <code>optional double distance = 4;</code>
     */
    public double getDistance() {
      return distance_;
    }

    public static final int EDGEDISTANCE_FIELD_NUMBER = 5;
    private double edgeDistance_;
    /**
     * <code>optional double edgeDistance = 5;</code>
     */
    public double getEdgeDistance() {
      return edgeDistance_;
    }

    public static final int EDGESIDE_FIELD_NUMBER = 6;
    private volatile java.lang.Object edgeSide_;
    /**
     * <code>optional string edgeSide = 6;</code>
     */
    public java.lang.String getEdgeSide() {
      java.lang.Object ref = edgeSide_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        edgeSide_ = s;
        return s;
      }
    }
    /**
     * <code>optional string edgeSide = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEdgeSideBytes() {
      java.lang.Object ref = edgeSide_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        edgeSide_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (velocity_ != 0D) {
        output.writeDouble(1, velocity_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, direction_);
      }
      if (acceleration_ != 0D) {
        output.writeDouble(3, acceleration_);
      }
      if (distance_ != 0D) {
        output.writeDouble(4, distance_);
      }
      if (edgeDistance_ != 0D) {
        output.writeDouble(5, edgeDistance_);
      }
      if (!getEdgeSideBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, edgeSide_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (velocity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, velocity_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, direction_);
      }
      if (acceleration_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, acceleration_);
      }
      if (distance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, distance_);
      }
      if (edgeDistance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, edgeDistance_);
      }
      if (!getEdgeSideBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, edgeSide_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Drive parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.VcuCmdMsg.Drive prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Drive}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Drive)
        com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Drive_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Drive_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.VcuCmdMsg.Drive.class, com.addrobots.protobuf.VcuCmdMsg.Drive.Builder.class);
      }

      // Construct using com.addrobots.protobuf.VcuCmdMsg.Drive.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        velocity_ = 0D;

        direction_ = "";

        acceleration_ = 0D;

        distance_ = 0D;

        edgeDistance_ = 0D;

        edgeSide_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Drive_descriptor;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Drive getDefaultInstanceForType() {
        return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
      }

      public com.addrobots.protobuf.VcuCmdMsg.Drive build() {
        com.addrobots.protobuf.VcuCmdMsg.Drive result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Drive buildPartial() {
        com.addrobots.protobuf.VcuCmdMsg.Drive result = new com.addrobots.protobuf.VcuCmdMsg.Drive(this);
        result.velocity_ = velocity_;
        result.direction_ = direction_;
        result.acceleration_ = acceleration_;
        result.distance_ = distance_;
        result.edgeDistance_ = edgeDistance_;
        result.edgeSide_ = edgeSide_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.VcuCmdMsg.Drive) {
          return mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Drive)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.VcuCmdMsg.Drive other) {
        if (other == com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance()) return this;
        if (other.getVelocity() != 0D) {
          setVelocity(other.getVelocity());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (other.getAcceleration() != 0D) {
          setAcceleration(other.getAcceleration());
        }
        if (other.getDistance() != 0D) {
          setDistance(other.getDistance());
        }
        if (other.getEdgeDistance() != 0D) {
          setEdgeDistance(other.getEdgeDistance());
        }
        if (!other.getEdgeSide().isEmpty()) {
          edgeSide_ = other.edgeSide_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.VcuCmdMsg.Drive parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.VcuCmdMsg.Drive) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double velocity_ ;
      /**
       * <code>optional double velocity = 1;</code>
       */
      public double getVelocity() {
        return velocity_;
      }
      /**
       * <code>optional double velocity = 1;</code>
       */
      public Builder setVelocity(double value) {
        
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double velocity = 1;</code>
       */
      public Builder clearVelocity() {
        
        velocity_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>optional string direction = 2;</code>
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private double acceleration_ ;
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public double getAcceleration() {
        return acceleration_;
      }
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public Builder setAcceleration(double value) {
        
        acceleration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public Builder clearAcceleration() {
        
        acceleration_ = 0D;
        onChanged();
        return this;
      }

      private double distance_ ;
      /**
       * <code>optional double distance = 4;</code>
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>optional double distance = 4;</code>
       */
      public Builder setDistance(double value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double distance = 4;</code>
       */
      public Builder clearDistance() {
        
        distance_ = 0D;
        onChanged();
        return this;
      }

      private double edgeDistance_ ;
      /**
       * <code>optional double edgeDistance = 5;</code>
       */
      public double getEdgeDistance() {
        return edgeDistance_;
      }
      /**
       * <code>optional double edgeDistance = 5;</code>
       */
      public Builder setEdgeDistance(double value) {
        
        edgeDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double edgeDistance = 5;</code>
       */
      public Builder clearEdgeDistance() {
        
        edgeDistance_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object edgeSide_ = "";
      /**
       * <code>optional string edgeSide = 6;</code>
       */
      public java.lang.String getEdgeSide() {
        java.lang.Object ref = edgeSide_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          edgeSide_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string edgeSide = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEdgeSideBytes() {
        java.lang.Object ref = edgeSide_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          edgeSide_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string edgeSide = 6;</code>
       */
      public Builder setEdgeSide(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        edgeSide_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string edgeSide = 6;</code>
       */
      public Builder clearEdgeSide() {
        
        edgeSide_ = getDefaultInstance().getEdgeSide();
        onChanged();
        return this;
      }
      /**
       * <code>optional string edgeSide = 6;</code>
       */
      public Builder setEdgeSideBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        edgeSide_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Drive)
    }

    // @@protoc_insertion_point(class_scope:Drive)
    private static final com.addrobots.protobuf.VcuCmdMsg.Drive DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.VcuCmdMsg.Drive();
    }

    public static com.addrobots.protobuf.VcuCmdMsg.Drive getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Drive>
        PARSER = new com.google.protobuf.AbstractParser<Drive>() {
      public Drive parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Drive(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Drive> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Drive> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.VcuCmdMsg.Drive getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrbitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Orbit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double velocity = 1;</code>
     */
    double getVelocity();

    /**
     * <code>optional string direction = 2;</code>
     */
    java.lang.String getDirection();
    /**
     * <code>optional string direction = 2;</code>
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>optional double acceleration = 3;</code>
     */
    double getAcceleration();

    /**
     * <code>optional double degrees = 4;</code>
     */
    double getDegrees();
  }
  /**
   * Protobuf type {@code Orbit}
   */
  public  static final class Orbit extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Orbit)
      OrbitOrBuilder {
    // Use Orbit.newBuilder() to construct.
    private Orbit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Orbit() {
      velocity_ = 0D;
      direction_ = "";
      acceleration_ = 0D;
      degrees_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Orbit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              velocity_ = input.readDouble();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 25: {

              acceleration_ = input.readDouble();
              break;
            }
            case 33: {

              degrees_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Orbit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Orbit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.VcuCmdMsg.Orbit.class, com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder.class);
    }

    public static final int VELOCITY_FIELD_NUMBER = 1;
    private double velocity_;
    /**
     * <code>optional double velocity = 1;</code>
     */
    public double getVelocity() {
      return velocity_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object direction_;
    /**
     * <code>optional string direction = 2;</code>
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>optional string direction = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCELERATION_FIELD_NUMBER = 3;
    private double acceleration_;
    /**
     * <code>optional double acceleration = 3;</code>
     */
    public double getAcceleration() {
      return acceleration_;
    }

    public static final int DEGREES_FIELD_NUMBER = 4;
    private double degrees_;
    /**
     * <code>optional double degrees = 4;</code>
     */
    public double getDegrees() {
      return degrees_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (velocity_ != 0D) {
        output.writeDouble(1, velocity_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, direction_);
      }
      if (acceleration_ != 0D) {
        output.writeDouble(3, acceleration_);
      }
      if (degrees_ != 0D) {
        output.writeDouble(4, degrees_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (velocity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, velocity_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, direction_);
      }
      if (acceleration_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, acceleration_);
      }
      if (degrees_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, degrees_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Orbit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.VcuCmdMsg.Orbit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Orbit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Orbit)
        com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Orbit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Orbit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.VcuCmdMsg.Orbit.class, com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder.class);
      }

      // Construct using com.addrobots.protobuf.VcuCmdMsg.Orbit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        velocity_ = 0D;

        direction_ = "";

        acceleration_ = 0D;

        degrees_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Orbit_descriptor;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Orbit getDefaultInstanceForType() {
        return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
      }

      public com.addrobots.protobuf.VcuCmdMsg.Orbit build() {
        com.addrobots.protobuf.VcuCmdMsg.Orbit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Orbit buildPartial() {
        com.addrobots.protobuf.VcuCmdMsg.Orbit result = new com.addrobots.protobuf.VcuCmdMsg.Orbit(this);
        result.velocity_ = velocity_;
        result.direction_ = direction_;
        result.acceleration_ = acceleration_;
        result.degrees_ = degrees_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.VcuCmdMsg.Orbit) {
          return mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Orbit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.VcuCmdMsg.Orbit other) {
        if (other == com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance()) return this;
        if (other.getVelocity() != 0D) {
          setVelocity(other.getVelocity());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (other.getAcceleration() != 0D) {
          setAcceleration(other.getAcceleration());
        }
        if (other.getDegrees() != 0D) {
          setDegrees(other.getDegrees());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.VcuCmdMsg.Orbit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.VcuCmdMsg.Orbit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double velocity_ ;
      /**
       * <code>optional double velocity = 1;</code>
       */
      public double getVelocity() {
        return velocity_;
      }
      /**
       * <code>optional double velocity = 1;</code>
       */
      public Builder setVelocity(double value) {
        
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double velocity = 1;</code>
       */
      public Builder clearVelocity() {
        
        velocity_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>optional string direction = 2;</code>
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>optional string direction = 2;</code>
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private double acceleration_ ;
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public double getAcceleration() {
        return acceleration_;
      }
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public Builder setAcceleration(double value) {
        
        acceleration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double acceleration = 3;</code>
       */
      public Builder clearAcceleration() {
        
        acceleration_ = 0D;
        onChanged();
        return this;
      }

      private double degrees_ ;
      /**
       * <code>optional double degrees = 4;</code>
       */
      public double getDegrees() {
        return degrees_;
      }
      /**
       * <code>optional double degrees = 4;</code>
       */
      public Builder setDegrees(double value) {
        
        degrees_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double degrees = 4;</code>
       */
      public Builder clearDegrees() {
        
        degrees_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Orbit)
    }

    // @@protoc_insertion_point(class_scope:Orbit)
    private static final com.addrobots.protobuf.VcuCmdMsg.Orbit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.VcuCmdMsg.Orbit();
    }

    public static com.addrobots.protobuf.VcuCmdMsg.Orbit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Orbit>
        PARSER = new com.google.protobuf.AbstractParser<Orbit>() {
      public Orbit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Orbit(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Orbit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Orbit> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.VcuCmdMsg.Orbit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HaltOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Halt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double acceleration = 1;</code>
     */
    double getAcceleration();
  }
  /**
   * Protobuf type {@code Halt}
   */
  public  static final class Halt extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Halt)
      HaltOrBuilder {
    // Use Halt.newBuilder() to construct.
    private Halt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Halt() {
      acceleration_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Halt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              acceleration_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Halt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_Halt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.VcuCmdMsg.Halt.class, com.addrobots.protobuf.VcuCmdMsg.Halt.Builder.class);
    }

    public static final int ACCELERATION_FIELD_NUMBER = 1;
    private double acceleration_;
    /**
     * <code>optional double acceleration = 1;</code>
     */
    public double getAcceleration() {
      return acceleration_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (acceleration_ != 0D) {
        output.writeDouble(1, acceleration_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (acceleration_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, acceleration_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.Halt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.VcuCmdMsg.Halt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Halt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Halt)
        com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Halt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Halt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.VcuCmdMsg.Halt.class, com.addrobots.protobuf.VcuCmdMsg.Halt.Builder.class);
      }

      // Construct using com.addrobots.protobuf.VcuCmdMsg.Halt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        acceleration_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_Halt_descriptor;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Halt getDefaultInstanceForType() {
        return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
      }

      public com.addrobots.protobuf.VcuCmdMsg.Halt build() {
        com.addrobots.protobuf.VcuCmdMsg.Halt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.VcuCmdMsg.Halt buildPartial() {
        com.addrobots.protobuf.VcuCmdMsg.Halt result = new com.addrobots.protobuf.VcuCmdMsg.Halt(this);
        result.acceleration_ = acceleration_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.VcuCmdMsg.Halt) {
          return mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Halt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.VcuCmdMsg.Halt other) {
        if (other == com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance()) return this;
        if (other.getAcceleration() != 0D) {
          setAcceleration(other.getAcceleration());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.VcuCmdMsg.Halt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.VcuCmdMsg.Halt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double acceleration_ ;
      /**
       * <code>optional double acceleration = 1;</code>
       */
      public double getAcceleration() {
        return acceleration_;
      }
      /**
       * <code>optional double acceleration = 1;</code>
       */
      public Builder setAcceleration(double value) {
        
        acceleration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double acceleration = 1;</code>
       */
      public Builder clearAcceleration() {
        
        acceleration_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Halt)
    }

    // @@protoc_insertion_point(class_scope:Halt)
    private static final com.addrobots.protobuf.VcuCmdMsg.Halt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.VcuCmdMsg.Halt();
    }

    public static com.addrobots.protobuf.VcuCmdMsg.Halt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Halt>
        PARSER = new com.google.protobuf.AbstractParser<Halt>() {
      public Halt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Halt(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Halt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Halt> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.VcuCmdMsg.Halt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VcuWrapperMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VcuWrapperMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Drive drive = 1;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.Drive getDrive();
    /**
     * <code>optional .Drive drive = 1;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder getDriveOrBuilder();

    /**
     * <code>optional .Orbit orbit = 2;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.Orbit getOrbit();
    /**
     * <code>optional .Orbit orbit = 2;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder getOrbitOrBuilder();

    /**
     * <code>optional .Halt halt = 3;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.Halt getHalt();
    /**
     * <code>optional .Halt halt = 3;</code>
     */
    com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder getHaltOrBuilder();

    public com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code VcuWrapperMessage}
   */
  public  static final class VcuWrapperMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VcuWrapperMessage)
      VcuWrapperMessageOrBuilder {
    // Use VcuWrapperMessage.newBuilder() to construct.
    private VcuWrapperMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VcuWrapperMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VcuWrapperMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.addrobots.protobuf.VcuCmdMsg.Drive.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((com.addrobots.protobuf.VcuCmdMsg.Drive) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(com.addrobots.protobuf.VcuCmdMsg.Drive.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Drive) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(com.addrobots.protobuf.VcuCmdMsg.Orbit.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
            case 26: {
              com.addrobots.protobuf.VcuCmdMsg.Halt.Builder subBuilder = null;
              if (msgCase_ == 3) {
                subBuilder = ((com.addrobots.protobuf.VcuCmdMsg.Halt) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(com.addrobots.protobuf.VcuCmdMsg.Halt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.addrobots.protobuf.VcuCmdMsg.Halt) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_VcuWrapperMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.addrobots.protobuf.VcuCmdMsg.internal_static_VcuWrapperMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.class, com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      DRIVE(1),
      ORBIT(2),
      HALT(3),
      MSG_NOT_SET(0);
      private int value = 0;
      private MsgCase(int value) {
        this.value = value;
      }
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return DRIVE;
          case 2: return ORBIT;
          case 3: return HALT;
          case 0: return MSG_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int DRIVE_FIELD_NUMBER = 1;
    /**
     * <code>optional .Drive drive = 1;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.Drive getDrive() {
      if (msgCase_ == 1) {
         return (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
    }
    /**
     * <code>optional .Drive drive = 1;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder getDriveOrBuilder() {
      if (msgCase_ == 1) {
         return (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
    }

    public static final int ORBIT_FIELD_NUMBER = 2;
    /**
     * <code>optional .Orbit orbit = 2;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.Orbit getOrbit() {
      if (msgCase_ == 2) {
         return (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
    }
    /**
     * <code>optional .Orbit orbit = 2;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder getOrbitOrBuilder() {
      if (msgCase_ == 2) {
         return (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
    }

    public static final int HALT_FIELD_NUMBER = 3;
    /**
     * <code>optional .Halt halt = 3;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.Halt getHalt() {
      if (msgCase_ == 3) {
         return (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
    }
    /**
     * <code>optional .Halt halt = 3;</code>
     */
    public com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder getHaltOrBuilder() {
      if (msgCase_ == 3) {
         return (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_;
      }
      return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_);
      }
      if (msgCase_ == 3) {
        output.writeMessage(3, (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_);
      }
      if (msgCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VcuWrapperMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VcuWrapperMessage)
        com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_VcuWrapperMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_VcuWrapperMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.class, com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.Builder.class);
      }

      // Construct using com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.addrobots.protobuf.VcuCmdMsg.internal_static_VcuWrapperMessage_descriptor;
      }

      public com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage getDefaultInstanceForType() {
        return com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.getDefaultInstance();
      }

      public com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage build() {
        com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage buildPartial() {
        com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage result = new com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage(this);
        if (msgCase_ == 1) {
          if (driveBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = driveBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (orbitBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = orbitBuilder_.build();
          }
        }
        if (msgCase_ == 3) {
          if (haltBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = haltBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage) {
          return mergeFrom((com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage other) {
        if (other == com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case DRIVE: {
            mergeDrive(other.getDrive());
            break;
          }
          case ORBIT: {
            mergeOrbit(other.getOrbit());
            break;
          }
          case HALT: {
            mergeHalt(other.getHalt());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Drive, com.addrobots.protobuf.VcuCmdMsg.Drive.Builder, com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder> driveBuilder_;
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Drive getDrive() {
        if (driveBuilder_ == null) {
          if (msgCase_ == 1) {
            return (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return driveBuilder_.getMessage();
          }
          return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public Builder setDrive(com.addrobots.protobuf.VcuCmdMsg.Drive value) {
        if (driveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          driveBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public Builder setDrive(
          com.addrobots.protobuf.VcuCmdMsg.Drive.Builder builderForValue) {
        if (driveBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          driveBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public Builder mergeDrive(com.addrobots.protobuf.VcuCmdMsg.Drive value) {
        if (driveBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance()) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Drive.newBuilder((com.addrobots.protobuf.VcuCmdMsg.Drive) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            driveBuilder_.mergeFrom(value);
          }
          driveBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public Builder clearDrive() {
        if (driveBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          driveBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Drive.Builder getDriveBuilder() {
        return getDriveFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder getDriveOrBuilder() {
        if ((msgCase_ == 1) && (driveBuilder_ != null)) {
          return driveBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Drive drive = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Drive, com.addrobots.protobuf.VcuCmdMsg.Drive.Builder, com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder> 
          getDriveFieldBuilder() {
        if (driveBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Drive.getDefaultInstance();
          }
          driveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.addrobots.protobuf.VcuCmdMsg.Drive, com.addrobots.protobuf.VcuCmdMsg.Drive.Builder, com.addrobots.protobuf.VcuCmdMsg.DriveOrBuilder>(
                  (com.addrobots.protobuf.VcuCmdMsg.Drive) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return driveBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Orbit, com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder, com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder> orbitBuilder_;
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Orbit getOrbit() {
        if (orbitBuilder_ == null) {
          if (msgCase_ == 2) {
            return (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return orbitBuilder_.getMessage();
          }
          return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public Builder setOrbit(com.addrobots.protobuf.VcuCmdMsg.Orbit value) {
        if (orbitBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          orbitBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public Builder setOrbit(
          com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder builderForValue) {
        if (orbitBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          orbitBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public Builder mergeOrbit(com.addrobots.protobuf.VcuCmdMsg.Orbit value) {
        if (orbitBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance()) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Orbit.newBuilder((com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            orbitBuilder_.mergeFrom(value);
          }
          orbitBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public Builder clearOrbit() {
        if (orbitBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          orbitBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder getOrbitBuilder() {
        return getOrbitFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder getOrbitOrBuilder() {
        if ((msgCase_ == 2) && (orbitBuilder_ != null)) {
          return orbitBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Orbit orbit = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Orbit, com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder, com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder> 
          getOrbitFieldBuilder() {
        if (orbitBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Orbit.getDefaultInstance();
          }
          orbitBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.addrobots.protobuf.VcuCmdMsg.Orbit, com.addrobots.protobuf.VcuCmdMsg.Orbit.Builder, com.addrobots.protobuf.VcuCmdMsg.OrbitOrBuilder>(
                  (com.addrobots.protobuf.VcuCmdMsg.Orbit) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return orbitBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Halt, com.addrobots.protobuf.VcuCmdMsg.Halt.Builder, com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder> haltBuilder_;
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Halt getHalt() {
        if (haltBuilder_ == null) {
          if (msgCase_ == 3) {
            return (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
        } else {
          if (msgCase_ == 3) {
            return haltBuilder_.getMessage();
          }
          return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public Builder setHalt(com.addrobots.protobuf.VcuCmdMsg.Halt value) {
        if (haltBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          haltBuilder_.setMessage(value);
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public Builder setHalt(
          com.addrobots.protobuf.VcuCmdMsg.Halt.Builder builderForValue) {
        if (haltBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          haltBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public Builder mergeHalt(com.addrobots.protobuf.VcuCmdMsg.Halt value) {
        if (haltBuilder_ == null) {
          if (msgCase_ == 3 &&
              msg_ != com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance()) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Halt.newBuilder((com.addrobots.protobuf.VcuCmdMsg.Halt) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 3) {
            haltBuilder_.mergeFrom(value);
          }
          haltBuilder_.setMessage(value);
        }
        msgCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public Builder clearHalt() {
        if (haltBuilder_ == null) {
          if (msgCase_ == 3) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 3) {
            msgCase_ = 0;
            msg_ = null;
          }
          haltBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.Halt.Builder getHaltBuilder() {
        return getHaltFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      public com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder getHaltOrBuilder() {
        if ((msgCase_ == 3) && (haltBuilder_ != null)) {
          return haltBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 3) {
            return (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_;
          }
          return com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Halt halt = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.addrobots.protobuf.VcuCmdMsg.Halt, com.addrobots.protobuf.VcuCmdMsg.Halt.Builder, com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder> 
          getHaltFieldBuilder() {
        if (haltBuilder_ == null) {
          if (!(msgCase_ == 3)) {
            msg_ = com.addrobots.protobuf.VcuCmdMsg.Halt.getDefaultInstance();
          }
          haltBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.addrobots.protobuf.VcuCmdMsg.Halt, com.addrobots.protobuf.VcuCmdMsg.Halt.Builder, com.addrobots.protobuf.VcuCmdMsg.HaltOrBuilder>(
                  (com.addrobots.protobuf.VcuCmdMsg.Halt) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 3;
        onChanged();;
        return haltBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VcuWrapperMessage)
    }

    // @@protoc_insertion_point(class_scope:VcuWrapperMessage)
    private static final com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage();
    }

    public static com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VcuWrapperMessage>
        PARSER = new com.google.protobuf.AbstractParser<VcuWrapperMessage>() {
      public VcuWrapperMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new VcuWrapperMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<VcuWrapperMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VcuWrapperMessage> getParserForType() {
      return PARSER;
    }

    public com.addrobots.protobuf.VcuCmdMsg.VcuWrapperMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Drive_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Drive_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Orbit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Orbit_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Halt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Halt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VcuWrapperMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VcuWrapperMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017VcuCmdMsg.proto\"|\n\005Drive\022\020\n\010velocity\030\001" +
      " \001(\001\022\021\n\tdirection\030\002 \001(\t\022\024\n\014acceleration\030" +
      "\003 \001(\001\022\020\n\010distance\030\004 \001(\001\022\024\n\014edgeDistance\030" +
      "\005 \001(\001\022\020\n\010edgeSide\030\006 \001(\t\"S\n\005Orbit\022\020\n\010velo" +
      "city\030\001 \001(\001\022\021\n\tdirection\030\002 \001(\t\022\024\n\014acceler" +
      "ation\030\003 \001(\001\022\017\n\007degrees\030\004 \001(\001\"\034\n\004Halt\022\024\n\014" +
      "acceleration\030\001 \001(\001\"c\n\021VcuWrapperMessage\022" +
      "\027\n\005drive\030\001 \001(\0132\006.DriveH\000\022\027\n\005orbit\030\002 \001(\0132" +
      "\006.OrbitH\000\022\025\n\004halt\030\003 \001(\0132\005.HaltH\000B\005\n\003msgB" +
      "\030\n\026com.addrobots.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Drive_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Drive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Drive_descriptor,
        new java.lang.String[] { "Velocity", "Direction", "Acceleration", "Distance", "EdgeDistance", "EdgeSide", });
    internal_static_Orbit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Orbit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Orbit_descriptor,
        new java.lang.String[] { "Velocity", "Direction", "Acceleration", "Degrees", });
    internal_static_Halt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Halt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Halt_descriptor,
        new java.lang.String[] { "Acceleration", });
    internal_static_VcuWrapperMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_VcuWrapperMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VcuWrapperMessage_descriptor,
        new java.lang.String[] { "Drive", "Orbit", "Halt", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
